name: birds-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.2.2
  - matplotlib==3.7.5
  - seaborn==0.12.2
  - jupyterlab==4.2.5
  - torch==2.4.0+cpu
  - torchaudio==2.4.0+cpu
  - torchinfo==1.8.0
  - torchmetrics==1.4.2
  - pytorch-ignite==0.5.1
  - pytorch-lightning==2.4.0
  - torchvision==0.19.0+cpu
  - pip
  - pip:
      - kaggle  # To ensure Kaggle API works in the environment
